export const CAR_BRANDS = [
  { key: "acura", label: "Acura", count: 11 },
  { key: "alfa_romeo", label: "Alfa Romeo", count: 17 },
  { key: "amuse", label: "Amuse", count: 6 },
  { key: "audi", label: "Audi", count: 0 },
  { key: "autobacs", label: "Autobacs", count: 0 },
  { key: "bmw", label: "BMW", count: 0 },
  { key: "cadillac", label: "Cadillac", count: 0 },
  { key: "chevrolet", label: "Chevrolet", count: 0 },
  { key: "chrysler", label: "Chrysler", count: 0 },
  { key: "citroen", label: "Citroën", count: 0 },
  { key: "daihatsu", label: "Daihatsu", count: 0 },
  { key: "dodge", label: "Dodge", count: 0 },
  { key: "ferrari", label: "Ferrari", count: 0 },
  { key: "fiat", label: "Fiat", count: 0 },
  { key: "ford", label: "Ford", count: 0 },
  { key: "gazoo_racing", label: "Gazoo Racing", count: 0 },
  { key: "gran_turismo", label: "Gran Turismo", count: 0 },
  { key: "honda", label: "Honda", count: 0 },
  { key: "hyundai", label: "Hyundai", count: 0 },
  { key: "infiniti", label: "Infiniti", count: 0 },
  { key: "isuzu", label: "Isuzu", count: 0 },
  { key: "jaguar", label: "Jaguar", count: 0 },
  { key: "jeep", label: "Jeep", count: 0 },
  { key: "kia", label: "Kia", count: 0 },
  { key: "lamborghini", label: "Lamborghini", count: 0 },
  { key: "lancia", label: "Lancia", count: 0 },
  { key: "land_rover", label: "Land Rover", count: 0 },
  { key: "lexus", label: "Lexus", count: 0 },
  { key: "lotus", label: "Lotus", count: 0 },
  { key: "maserati", label: "Maserati", count: 0 },
  { key: "mazda", label: "Mazda", count: 0 },
  { key: "mercedes_benz", label: "Mercedes-Benz", count: 0 },
  { key: "mini", label: "MINI", count: 0 },
  { key: "mitsubishi", label: "Mitsubishi", count: 0 },
  { key: "nissan", label: "Nissan", count: 0 },
  { key: "opera", label: "Opera", count: 0 },
  { key: "pagani", label: "Pagani", count: 0 },
  { key: "peugeot", label: "Peugeot", count: 0 },
  { key: "plymouth", label: "Plymouth", count: 0 },
  { key: "pontiac", label: "Pontiac", count: 0 },
  { key: "premium", label: "Premium", count: 0 },
  { key: "renault", label: "Renault", count: 0 },
  { key: "re_amemiya", label: "RE Amemiya", count: 0 },
  { key: "ruf", label: "RUF", count: 0 },
  { key: "saleen", label: "Saleen", count: 0 },
  { key: "scion", label: "Scion", count: 0 },
  { key: "srt", label: "SRT", count: 0 },
  { key: "subaru", label: "Subaru", count: 0 },
  { key: "suzuki", label: "Suzuki", count: 0 },
  { key: "tesla", label: "Tesla", count: 0 },
  { key: "toyota", label: "Toyota", count: 0 },
  { key: "triumph", label: "Triumph", count: 0 },
  { key: "tv_r", label: "TVR", count: 0 },
  { key: "vauxhall", label: "Vauxhall", count: 0 },
  { key: "venturi", label: "Venturi", count: 0 },
  { key: "volkswagen", label: "Volkswagen", count: 0 },
  { key: "volvo", label: "Volvo", count: 0 },
];