export const CAR_BRANDS = [
  { key: "AC_Cars", label: "AC Cars", count: 1 },
  { key: "AEM", label: "AEM", count: 1 },
  { key: "Abarth", label: "Abarth", count: 3 },
  { key: "Acura", label: "Acura", count: 11 },
  { key: "Alfa_Romeo", label: "Alfa Romeo", count: 17 },
  { key: "Alpine", label: "Alpine", count: 6 },
  { key: "Amuse", label: "Amuse", count: 6 },
  { key: "Art_Morrison", label: "Art Morrison", count: 1 },
  { key: "Aston_Martin", label: "Aston Martin", count: 8 },
  { key: "Audi", label: "Audi", count: 39 },
  { key: "Autobacs", label: "Autobacs", count: 4 },
  { key: "Autobianchi", label: "Autobianchi", count: 1 },
  { key: "Ayrton_Senna", label: "Ayrton Senna", count: 3 },
  { key: "BLITZ", label: "BLITZ", count: 2 },
  { key: "BMW", label: "BMW", count: 30 },
  { key: "Bentley", label: "Bentley", count: 1 },
  { key: "Bugatti", label: "Bugatti", count: 2 },
  { key: "Buick", label: "Buick", count: 2 },
  { key: "Cadillac", label: "Cadillac", count: 2 },
  { key: "Callaway", label: "Callaway", count: 1 },
  { key: "Caterham", label: "Caterham", count: 1 },
  { key: "Chaparral", label: "Chaparral", count: 3 },
  { key: "Chevrolet", label: "Chevrolet", count: 49 },
  { key: "Chrysler", label: "Chrysler", count: 4 },
  { key: "Citroën", label: "Citroën", count: 11 },
  { key: "Cizeta", label: "Cizeta", count: 2 },
  { key: "DMC", label: "DMC", count: 1 },
  { key: "Daihatsu", label: "Daihatsu", count: 16 },
  { key: "DeltaWing", label: "DeltaWing", count: 2 },
  { key: "Dodge", label: "Dodge", count: 4 },
  { key: "Dome", label: "Dome", count: 1 },
  { key: "Eagle", label: "Eagle", count: 1 },
  { key: "Ferrari", label: "Ferrari", count: 16 },
  { key: "Fiat", label: "Fiat", count: 9 },
  { key: "Fisker", label: "Fisker", count: 1 },
  { key: "Ford", label: "Ford", count: 36 },
  { key: "Gillet", label: "Gillet", count: 1 },
  { key: "Gran_Turismo", label: "Gran Turismo", count: 17 },
  { key: "Grand_Touring_Garage", label: "Grand Touring Garage", count: 1 },
  { key: "HKS", label: "HKS", count: 2 },
  { key: "HPA_Motorsports", label: "HPA Motorsports", count: 2 },
  { key: "High_End_Performance", label: "High End Performance", count: 1 },
  { key: "Holden", label: "Holden", count: 2 },
  { key: "Hommell", label: "Hommell", count: 1 },
  { key: "Honda", label: "Honda", count: 110 },
  { key: "Hudson", label: "Hudson", count: 1 },
  { key: "Hyundai", label: "Hyundai", count: 10 },
  { key: "Infiniti", label: "Infiniti", count: 7 },
  { key: "Isuzu", label: "Isuzu", count: 4 },
  { key: "Jaguar", label: "Jaguar", count: 13 },
  { key: "Jay_leno", label: "Jay leno", count: 2 },
  { key: "KTM", label: "KTM", count: 3 },
  { key: "Lamborghini", label: "Lamborghini", count: 12 },
  { key: "Lancia", label: "Lancia", count: 6 },
  { key: "Land_Rover", label: "Land Rover", count: 2 },
  { key: "Lexus", label: "Lexus", count: 25 },
  { key: "Light_Car_Company", label: "Light Car Company", count: 1 },
  { key: "Lister", label: "Lister", count: 1 },
  { key: "Lotus", label: "Lotus", count: 21 },
  { key: "MG", label: "MG", count: 2 },
  { key: "MINI", label: "MINI", count: 9 },
  { key: "Marcos", label: "Marcos", count: 1 },
  { key: "Maserati", label: "Maserati", count: 1 },
  { key: "Mazda", label: "Mazda", count: 102 },
  { key: "McLaren", label: "McLaren", count: 5 },
  { key: "Mercedes-Benz", label: "Mercedes-Benz", count: 27 },
  { key: "Mercury", label: "Mercury", count: 1 },
  { key: "Mine's", label: "Mine's", count: 3 },
  { key: "Mitsubishi", label: "Mitsubishi", count: 74 },
  { key: "Monster_Sport", label: "Monster Sport", count: 2 },
  { key: "Mugen", label: "Mugen", count: 1 },
  { key: "NISMO", label: "NISMO", count: 7 },
  { key: "Nissan", label: "Nissan", count: 153 },
  { key: "Opel", label: "Opel", count: 7 },
  { key: "Opera_Performance", label: "Opera Performance", count: 2 },
  { key: "Oullim_Motors", label: "Oullim Motors", count: 1 },
  { key: "Pagani", label: "Pagani", count: 8 },
  { key: "Panoz", label: "Panoz", count: 1 },
  { key: "Pescarolo", label: "Pescarolo", count: 3 },
  { key: "Peugeot", label: "Peugeot", count: 19 },
  { key: "Plymouth", label: "Plymouth", count: 4 },
  { key: "Pontiac", label: "Pontiac", count: 6 },
  { key: "Pozzi_MotorSports", label: "Pozzi MotorSports", count: 1 },
  { key: "RE_Amemiya", label: "RE Amemiya", count: 4 },
  { key: "RUF", label: "RUF", count: 5 },
  { key: "Ram", label: "Ram", count: 1 },
  { key: "Renault_Sport", label: "Renault Sport", count: 15 },
  { key: "Renault", label: "Renault", count: 5 },
  { key: "SRT", label: "SRT", count: 18 },
  { key: "Saleen", label: "Saleen", count: 1 },
  { key: "Scion", label: "Scion", count: 3 },
  { key: "Seat", label: "Seat", count: 1 },
  { key: "Shelby", label: "Shelby", count: 7 },
  { key: "Spoon", label: "Spoon", count: 6 },
  { key: "Spyker", label: "Spyker", count: 1 },
  { key: "Stielow_Engineering", label: "Stielow Engineering", count: 1 },
  { key: "Subaru", label: "Subaru", count: 44 },
  { key: "Suzuki", label: "Suzuki", count: 16 },
  { key: "TRD", label: "TRD", count: 1 },
  { key: "TRIAL", label: "TRIAL", count: 1 },
  { key: "TVR", label: "TVR", count: 8 },
  { key: "Tajima", label: "Tajima", count: 1 },
  { key: "Tesla_Motors", label: "Tesla Motors", count: 3 },
  { key: "Tom's", label: "Tom's", count: 1 },
  { key: "Tommykaira", label: "Tommykaira", count: 2 },
  { key: "Toyota", label: "Toyota", count: 103 },
  { key: "Triumph", label: "Triumph", count: 1 },
  { key: "Vauxhall", label: "Vauxhall", count: 7 },
  { key: "Volkswagen", label: "Volkswagen", count: 28 },
  { key: "Volvo", label: "Volvo", count: 3 }
];